name: Firebase Trigger
description: Update a field in your firebase database
author: Jeremy Shore
inputs:
  firebaseConfig:
    description: Admin config json for connecting to application
  databaseType:
    description: Either `realtime` or `firestore`
    default: realtime
  path:
    description: Path to what you want to set in your database
    required: true
  doc:
    description: Document to set for firestore
  value:
    description: Value to be set
runs:
  using: node12
  main: dist/index.js